### ISSUE TITLE
Add metadata to all google drive files. Unambiguously connect a metadata term with a google drive folder.

### ISSUE THREAD

**Issue by fragagou** [imox2/gdoc-metadata-adder#1]
drive.google.com refused to connect
That's the error i get. Also, is there a general way to add metadata to all google drive files?
Also, is there away to unambiguously connect a metadata term with a google drive folder (even though we know the google drive folders have hierarchy (a personal, one that makes sense to us)? 
Thanx

**Comment by imox2** [comment]
@fragagou can you tell more about the error.  Possibly a screenshot of the error? Where you able to use it before and now can't?

- Also, is there a general way to add metadata to all google drive files?
    Well, you can use google drive api in a script to achieve that. 

- Also, is there away to unambiguously connect a metadata term with a google drive folder ?
   Can you please elaborate? Did you mean add metadata to a google drive folder?
